env:
  browser: true
  es6: true
extends:
  - airbnb-base
plugins:
  - "import"
  - "react"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
